config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  root 'landings#show'
  resources :animals
  resources :users

end

app/models/animal.rb
class Animal < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
    @animals = Animal.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController

  def show
    if current_user
      redirect_to user_path(current_user)
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/index.html.haml
.container
  .jumbotron
    %h2 Animals on Sale
    %table.table
      %tr
        %th Name
        %th Weight
        %th Breed
        %th Feed
      - @animals.each do |animal|
        %tr
          %td= link_to animal.name, animal
          %td= animal.live
          %td= animal.breed
          %td= animal.feed

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: "utf-8"}
    %meta{ content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{ content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{ content: "", name: "description"}
    %meta{ content: "", name: "author"}
    %title MeatUp

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar" }, aria: { expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "MeatUp", "#", class: "navbar-brand"
        #navbar.collapse.navbar-collapse.pull-right
          %ul.nav.navbar-nav
            %li= link_to "Animals on Sale", animals_path
            - if current_user
              %li= link_to "Profile", edit_user_registration_path(current_user)
            - else
              %li= link_to "Sign In", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{ type: "button", data: {dismiss: "alert"} }
            %span{ aria: { hidden: "true" } } &times;
            %span.sr-only Close
          = msg
      = yield